chore(chart): add nauth-crds complementary crds-only chart (#69)
In https://github.com/WirelessCar/nauth/issues/62, we discussed a use
case when it is currently not possible to use `nauth` as a dependency
chart when also using those CRDs in parent:

```
❯ helm create my-chart
Creating my-chart
❯ cd my-chart

❯ echo "dependencies:
  - name: nauth
    version: \"0.2.0\"
    repository: \"oci://ghcr.io/wirelesscar\"" >> Chart.yaml
❯ helm dependency update

❯ curl -L \
  https://raw.githubusercontent.com/WirelessCar/nauth/refs/heads/main/examples/nauth/manifests/scenarios/simple-account/simple-account.yaml \
  -o templates/simple-account.yaml

❯ minikube start
❯ helm install my-chart-release .
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "example-account" namespace: "simple-account" from "": no matches for kind "Account" in version "nauth.io/v1alpha1"
ensure CRDs are installed first, resource mapping not found for name: "example-user" namespace: "simple-account" from "": no matches for kind "User" in version "nauth.io/v1alpha1"
ensure CRDs are installed first]
```

This happens because CRDs rendered via `templates/` are installed at the
same time as everything else. Kubernetes doesn’t register them in time
for CR validation unlike it would with `crds/` folder.

In that issue a suggestion was to create a separate chart with crds
only.

This change adds a complementary `nauth-crds` that contains only crds
and plays along well with the main chart with `crds.install=false`.

By submitting a request, I represent that you have the right to license
your contribution to the community, and agree that your contributions
are
licensed under the [Apache-2.0
license](https://github.com/WirelessCar/nauth/blob/cbb74517e0737094c1ecf4f38dbb2c5d1f004653/LICENSE).